@Transactions = new Mongo.Collection 'transactions'
@Projects = new Mongo.Collection 'projects'
@Verifications = new Mongo.Collection 'verifications'
@Actions = new Mongo.Collection 'actions'
@Shares = new Mongo.Collection 'shares'
@Messages = new Mongo.Collection 'messages'
@Organisations = new Mongo.Collection 'organisations'
@History = new Mongo.Collection 'history'
@Words = new Mongo.Collection 'words'

@Objects = new Mongo.Collection 'objects'
