@Transactions = new Mongo.Collection 'transactions'
@Projects = new Mongo.Collection 'projects'
@Verifications = new Mongo.Collection 'verifications'
@Actions = new Mongo.Collection 'actions'
@Shares = new Mongo.Collection 'shares'
@Messages = new Mongo.Collection 'messages'
@Organisations = new Mongo.Collection 'organisations'
@History = new Mongo.Collection 'history'
@Words = new Mongo.Collection 'words'

@Elements = new Mongo.Collection 'elements'
@Relations = new Mongo.Collection 'relations'
@Events = new Mongo.Collection 'events'
