Meteor.subscribe 'People'
Meteor.subscribe 'Transactions'
Meteor.subscribe 'Projects'
Meteor.subscribe 'Verifications'
Meteor.subscribe 'Actions'
Meteor.subscribe 'Shares'
Meteor.subscribe 'Messages'
Meteor.subscribe 'Organisations'
Meteor.subscribe 'History'
Meteor.subscribe 'Words'

Meteor.subscribe 'Relations'
Meteor.subscribe 'Elements'
Meteor.subscribe 'Events'
